config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :weather_events
  resources :stations
  resources :messages
  resources :user_advices
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins

  root 'static_pages#home'

  resources :advices do
    resources :choices
  end
  resources :rules do
    resources :rule_advices
  end

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :sent, :time_sent, :user_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sent %><br>
    <%= f.check_box :sent %>
  </div>
  <div class="field">
    <%= f.label :time_sent %><br>
    <%= f.datetime_select :time_sent %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select(:user_id, User.all, :id, :email, {prompt: true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Sent</th>
      <th>Time sent</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.sent %></td>
        <td><%= message.time_sent %></td>
        <td><%= message.user.email %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Sent:</strong>
  <%= @message.sent %>
</p>

<p>
  <strong>Time sent:</strong>
  <%= @message.time_sent %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user.email %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>