config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :weather_events
  resources :stations
  resources :messages
  resources :user_advices
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins

  root 'static_pages#home'

  resources :advices do
    resources :choices
  end
  resources :rules do
    resources :rule_advices
  end

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/models/station.rb
class Station < ActiveRecord::Base
	has_many :users
	has_many :rules

	validates :name, presence: true
	validates :station_bom_id, presence: true

	validates :ave_max_jan, :ave_max_feb, :ave_max_mar, :ave_max_apr, :ave_max_may, :ave_max_june, numericality: true
	validates :ave_max_july, :ave_max_aug, :ave_max_sept, :ave_max_oct, :ave_max_nov, :ave_max_dec, numericality: true
	validates :ave_min_jan, :ave_min_feb, :ave_min_mar, :ave_min_apr, :ave_min_may, :ave_min_june, numericality: true
    validates :ave_min_july, :ave_min_aug, :ave_min_sept, :ave_min_oct, :ave_min_nov, :ave_min_dec, numericality: true
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :station_bom_id, :region, :ave_max_jan, :ave_min_jan, :ave_max_feb, :ave_min_feb, :ave_max_mar, :ave_min_mar, :ave_max_apr, :ave_min_apr, :ave_max_may, :ave_min_may, :ave_max_june, :ave_min_june, :ave_max_july, :ave_min_july, :ave_max_aug, :ave_min_aug, :ave_max_sept, :ave_min_sept, :ave_max_oct, :ave_min_oct, :ave_max_nov, :ave_min_nov, :ave_max_dec, :ave_min_dec)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  * indicates required fields
</p>

  <div class="field">
    <%= f.label :name %>*<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :station_bom_id %>*<br>
    <%= f.text_field :station_bom_id %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :ave_max_jan %>*<br>
    <%= f.text_field :ave_max_jan %>
  </div>
  <div class="field">
    <%= f.label :ave_min_jan %>*<br>
    <%= f.text_field :ave_min_jan %>
  </div>
  <div class="field">
    <%= f.label :ave_max_feb %>*<br>
    <%= f.text_field :ave_max_feb %>
  </div>
  <div class="field">
    <%= f.label :ave_min_feb %>*<br>
    <%= f.text_field :ave_min_feb %>
  </div>
  <div class="field">
    <%= f.label :ave_max_mar %>*<br>
    <%= f.text_field :ave_max_mar %>
  </div>
  <div class="field">
    <%= f.label :ave_min_mar %>*<br>
    <%= f.text_field :ave_min_mar %>
  </div>
  <div class="field">
    <%= f.label :ave_max_apr %>*<br>
    <%= f.text_field :ave_max_apr %>
  </div>
  <div class="field">
    <%= f.label :ave_min_apr %>*<br>
    <%= f.text_field :ave_min_apr %>
  </div>
  <div class="field">
    <%= f.label :ave_max_may %>*<br>
    <%= f.text_field :ave_max_may %>
  </div>
  <div class="field">
    <%= f.label :ave_min_may %>*<br>
    <%= f.text_field :ave_min_may %>
  </div>
  <div class="field">
    <%= f.label :ave_max_june %>*<br>
    <%= f.text_field :ave_max_june %>
  </div>
  <div class="field">
    <%= f.label :ave_min_june %>*<br>
    <%= f.text_field :ave_min_june %>
  </div>
  <div class="field">
    <%= f.label :ave_max_july %>*<br>
    <%= f.text_field :ave_max_july %>
  </div>
  <div class="field">
    <%= f.label :ave_min_july %>*<br>
    <%= f.text_field :ave_min_july %>
  </div>
  <div class="field">
    <%= f.label :ave_max_aug %>*<br>
    <%= f.text_field :ave_max_aug %>
  </div>
  <div class="field">
    <%= f.label :ave_min_aug %>*<br>
    <%= f.text_field :ave_min_aug %>
  </div>
  <div class="field">
    <%= f.label :ave_max_sept %>*<br>
    <%= f.text_field :ave_max_sept %>
  </div>
  <div class="field">
    <%= f.label :ave_min_sept %>*<br>
    <%= f.text_field :ave_min_sept %>
  </div>
  <div class="field">
    <%= f.label :ave_max_oct %>*<br>
    <%= f.text_field :ave_max_oct %>
  </div>
  <div class="field">
    <%= f.label :ave_min_oct %>*<br>
    <%= f.text_field :ave_min_oct %>
  </div>
  <div class="field">
    <%= f.label :ave_max_nov %>*<br>
    <%= f.text_field :ave_max_nov %>
  </div>
  <div class="field">
    <%= f.label :ave_min_nov %>*<br>
    <%= f.text_field :ave_min_nov %>
  </div>
  <div class="field">
    <%= f.label :ave_max_dec %>*<br>
    <%= f.text_field :ave_max_dec %>
  </div>
  <div class="field">
    <%= f.label :ave_min_dec %>*<br>
    <%= f.text_field :ave_min_dec %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bom Station ID</th>
      <th>Region</th>
      <th>Ave max jan</th>
      <th>Ave min jan</th>
      <th>Ave max feb</th>
      <th>Ave min feb</th>
      <th>Ave max mar</th>
      <th>Ave min mar</th>
      <th>Ave max apr</th>
      <th>Ave min apr</th>
      <th>Ave max may</th>
      <th>Ave min may</th>
      <th>Ave max june</th>
      <th>Ave min june</th>
      <th>Ave max july</th>
      <th>Ave min july</th>
      <th>Ave max aug</th>
      <th>Ave min aug</th>
      <th>Ave max sept</th>
      <th>Ave min sept</th>
      <th>Ave max oct</th>
      <th>Ave min oct</th>
      <th>Ave max nov</th>
      <th>Ave min nov</th>
      <th>Ave max dec</th>
      <th>Ave min dec</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.station_bom_id %></td>
        <td><%= station.region %></td>
        <td><%= station.ave_max_jan %></td>
        <td><%= station.ave_min_jan %></td>
        <td><%= station.ave_max_feb %></td>
        <td><%= station.ave_min_feb %></td>
        <td><%= station.ave_max_mar %></td>
        <td><%= station.ave_min_mar %></td>
        <td><%= station.ave_max_apr %></td>
        <td><%= station.ave_min_apr %></td>
        <td><%= station.ave_max_may %></td>
        <td><%= station.ave_min_may %></td>
        <td><%= station.ave_max_june %></td>
        <td><%= station.ave_min_june %></td>
        <td><%= station.ave_max_july %></td>
        <td><%= station.ave_min_july %></td>
        <td><%= station.ave_max_aug %></td>
        <td><%= station.ave_min_aug %></td>
        <td><%= station.ave_max_sept %></td>
        <td><%= station.ave_min_sept %></td>
        <td><%= station.ave_max_oct %></td>
        <td><%= station.ave_min_oct %></td>
        <td><%= station.ave_max_nov %></td>
        <td><%= station.ave_min_nov %></td>
        <td><%= station.ave_max_dec %></td>
        <td><%= station.ave_min_dec %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @station.region %>
</p>

<p>
  <strong>Bom Station ID:</strong>
  <%= @station.station_bom_id %>
</p>

<p>
  <strong>Ave max jan:</strong>
  <%= @station.ave_max_jan %>
</p>

<p>
  <strong>Ave min jan:</strong>
  <%= @station.ave_min_jan %>
</p>

<p>
  <strong>Ave max feb:</strong>
  <%= @station.ave_max_feb %>
</p>

<p>
  <strong>Ave min feb:</strong>
  <%= @station.ave_min_feb %>
</p>

<p>
  <strong>Ave max mar:</strong>
  <%= @station.ave_max_mar %>
</p>

<p>
  <strong>Ave min mar:</strong>
  <%= @station.ave_min_mar %>
</p>

<p>
  <strong>Ave max apr:</strong>
  <%= @station.ave_max_apr %>
</p>

<p>
  <strong>Ave min apr:</strong>
  <%= @station.ave_min_apr %>
</p>

<p>
  <strong>Ave max may:</strong>
  <%= @station.ave_max_may %>
</p>

<p>
  <strong>Ave min may:</strong>
  <%= @station.ave_min_may %>
</p>

<p>
  <strong>Ave max june:</strong>
  <%= @station.ave_max_june %>
</p>

<p>
  <strong>Ave min june:</strong>
  <%= @station.ave_min_june %>
</p>

<p>
  <strong>Ave max july:</strong>
  <%= @station.ave_max_july %>
</p>

<p>
  <strong>Ave min july:</strong>
  <%= @station.ave_min_july %>
</p>

<p>
  <strong>Ave max aug:</strong>
  <%= @station.ave_max_aug %>
</p>

<p>
  <strong>Ave min aug:</strong>
  <%= @station.ave_min_aug %>
</p>

<p>
  <strong>Ave max sept:</strong>
  <%= @station.ave_max_sept %>
</p>

<p>
  <strong>Ave min sept:</strong>
  <%= @station.ave_min_sept %>
</p>

<p>
  <strong>Ave max oct:</strong>
  <%= @station.ave_max_oct %>
</p>

<p>
  <strong>Ave min oct:</strong>
  <%= @station.ave_min_oct %>
</p>

<p>
  <strong>Ave max nov:</strong>
  <%= @station.ave_max_nov %>
</p>

<p>
  <strong>Ave min nov:</strong>
  <%= @station.ave_min_nov %>
</p>

<p>
  <strong>Ave max dec:</strong>
  <%= @station.ave_max_dec %>
</p>

<p>
  <strong>Ave min dec:</strong>
  <%= @station.ave_min_dec %>
</p>
<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>