config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :weather_events
  resources :stations
  resources :messages
  resources :user_advices
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins

  root 'static_pages#home'

  resources :advices do
    resources :choices
  end
  resources :rules do
    resources :rule_advices
  end

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/models/rule_advice.rb
class RuleAdvice < ActiveRecord::Base
  belongs_to :rule
  belongs_to :advice

  def self.linking_rules (advice)
  	Rule.all.each do |rule|
  	  rule_advice = advice.rule_advices.build(rule: rule)
  	  rule_advice.save
  	end
  end

  def self.linking_advices (rule)
  	Advice.all.each do |advice|
  	  rule_advice = rule.rule_advices.build(advice: advice)
  	  rule_advice.save
  	end
  end

end

app/controllers/rule_advices_controller.rb
class RuleAdvicesController < ApplicationController
  before_action :set_rule_advice, only: [:edit, :update]
  before_action :authenticate_admin!
  # GET /rule_advices
  # GET /rule_advices.json
  def index
    rule = Rule.find(params[:rule_id])
    @rule_advices = rule.rule_advices 
  end

  # GET /rule_advices/1/edit
  def edit
    @rule = Rule.find(params[:rule_id])
  end

  # PATCH/PUT /rule_advices/1
  # PATCH/PUT /rule_advices/1.json
  def update
    respond_to do |format|
      if @rule_advice.update(rule_advice_params)
        format.html { redirect_to rule_rule_advices_path(@rule_advice.rule), notice: 'Rule advice was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule_advice }
      else
        format.html { render :edit }
        format.json { render json: @rule_advice.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule_advice
      @rule_advice = RuleAdvice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_advice_params
      params.require(:rule_advice).permit(:value)
    end
end

app/helpers/rule_advices_helper.rb
module RuleAdvicesHelper
end

app/views/rule_advices/_form.html.erb
<%= form_for([@rule, @rule_advice]) do |f| %>
  <% if @rule_advice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule_advice.errors.count, "error") %> prohibited this rule_advice from being saved:</h2>

      <ul>
      <% @rule_advice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.collection_radio_buttons(:value, @rule_advice.advice.choices, :content, :content) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rule_advices/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing Rule Advice</h1>

<%= render 'form' %>

<%= link_to 'Back', rule_rule_advices_path(@rule_advice.rule) %>

app/views/rule_advices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices of Each Advice</h1>

<table>
  <thead>
    <tr>
      <th>Advice</th>
      <th>Value</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @rule_advices.each do |rule_advice| %>
      <tr>
        <td><%= rule_advice.advice.question %></td>
        <td><%= rule_advice.value %></td>
        <td><%= link_to 'Change Value', edit_rule_rule_advice_path(rule_advice.rule, rule_advice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rule_advices/new.html.erb
<h1>New Rule Advice</h1>

<%= render 'form' %>

<%= link_to 'Back', rule_advices_path %>

app/views/rule_advices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @rule_advice.value %>
</p>

<%= link_to 'Edit', edit_rule_advice_path(@rule_advice) %> |
<%= link_to 'Back', rule_advices_path %>