config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :weather_events
  resources :stations
  resources :messages
  resources :user_advices
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins

  root 'static_pages#home'

  resources :advices do
    resources :choices
  end
  resources :rules do
    resources :rule_advices
  end

  get '*unmatched_route', to: 'application#raise_not_found'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :advice
  validates :content, :message, presence: true
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:destroy]
  before_action :authenticate_admin!

  # POST /choices
  # POST /choices.json
  def create
    @advice = Advice.find(params[:advice_id])
    @choice = @advice.choices.create(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to advice_path(@advice), notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @advice = Advice.find(params[:advice_id])
    @choice = @advice.choices.find(params[:id])
    @choice.destroy

    respond_to do |format|
      format.html { redirect_to advice_path(@advice), notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:content, :message)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_for(@choice) do |f| %>
  <% if @choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% @choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :advice_id %><br>
    <%= f.text_field :advice_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Choices</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Message</th>
      <th>Advice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.content %></td>
        <td><%= choice.message %></td>
        <td><%= choice.advice_id %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @choice.content %>
</p>

<p>
  <strong>Message:</strong>
  <%= @choice.message %>
</p>

<p>
  <strong>Advice:</strong>
  <%= @choice.advice_id %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>